# Generated by Django 5.0.6 on 2024-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
            ],
        ),
    ]
