# Generated by Django 5.1.1 on 2024-09-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='arrival_date',
            new_name='traveling_date',
        ),
    ]
