# Generated by Django 5.1.1 on 2024-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0002_rename_arrival_date_train_traveling_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=50)),
                ('seat_class', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
