# Generated by Django 5.1.1 on 2024-09-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
