# Generated by Django 5.1.1 on 2024-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0004_seat_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSeat',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('traveling_date', models.DateField()),
                ('seat_class', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RunningTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('train_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_id', models.IntegerField()),
                ('traveling_date', models.DateField()),
                ('traveling_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='traveling_date',
        ),
        migrations.AddField(
            model_name='train',
            name='forward',
            field=models.BooleanField(default=True),
        ),
    ]
