# Generated by Django 5.1.1 on 2024-09-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0005_availableseat_runningtrain_trip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='train_id',
            new_name='trip_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='date',
        ),
    ]
