# Generated by Django 5.1.1 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickAndGoRail', '0006_rename_train_id_seat_trip_id_remove_seat_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableseat',
            old_name='train_id',
            new_name='trip_id',
        ),
        migrations.RemoveField(
            model_name='availableseat',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='availableseat',
            name='station',
        ),
        migrations.RemoveField(
            model_name='availableseat',
            name='traveling_date',
        ),
        migrations.RemoveField(
            model_name='train',
            name='forward',
        ),
        migrations.AddField(
            model_name='runningtrain',
            name='forward',
            field=models.BooleanField(default=True),
        ),
    ]
